import NavBar from '../components/NavBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <NavBar />
        </nav>
        {children}
        <footer style={{width:"100%", border:"1px solid red", padding:"10px"}}>
          <h1 style={{color:"white"}}>Este es el footer de toda la App</h1>
        </footer>
      </body>
    </html>
  )
}
